[Rainmeter]
Update=1000
AccurateText=1
DynamicWindowSize=1
BackgroundMode=2
SolidColor=0,0,0,1

[Variables]
Scale=1
TextColor=0,0,0,255
LineColor=0,0,0

FontMain=Anurati
FontSub=Quicksand

; ----------------------------------------------------
; MEASURES
; ----------------------------------------------------

[MeasureTime]
Measure=Time
Format=%H:%M

[MeasureDay]
Measure=Time
Format=%a
RegExpSubstitute=1
Substitute="^(.)(.)(.)$":"\1#CRLF#\2#CRLF#\3"

[MeasureDate]
Measure=Time
Format=%d
RegExpSubstitute=1
Substitute="^(.)(.)$":"\1#CRLF#\2"

[MeasureMonth]
Measure=Time
Format=%b
RegExpSubstitute=1
Substitute="^(.)(.)(.)$":"\1#CRLF#\2#CRLF#\3"

[MeasureYear]
Measure=Time
Format=%Y
RegExpSubstitute=1
Substitute="^(.)(.)(.)(.)$":"\1#CRLF#\2#CRLF#\3#CRLF#\4"

; ----------------------------------------------------
; DATE - MONTH - YEAR
; ----------------------------------------------------

[MeterDate]
Meter=String
MeasureName=MeasureDate
StringAlign=Center
StringCase=Upper
FontFace=#FontSub#
FontColor=#TextColor#
FontSize=(20*#Scale#)
X=(25*#Scale#)
Y=(35*#Scale#)
Text="%1"
InlineSetting=LineSpacing | 4
AntiAlias=1

[MeterMonth]
Meter=String
MeasureName=MeasureMonth
StringAlign=Center
StringCase=Upper
FontFace=#FontSub#
FontColor=#TextColor#
FontSize=(20*#Scale#)
X=(25*#Scale#)
Y=(120*#Scale#)
Text="%1"
InlineSetting=LineSpacing | 6
AntiAlias=1

[MeterYear]
Meter=String
MeasureName=MeasureYear
StringAlign=Center
StringCase=Upper
FontFace=#FontSub#
FontColor=#TextColor#
FontSize=(20*#Scale#)
X=(25*#Scale#)
Y=(230*#Scale#)
Text="%1"
InlineSetting=LineSpacing | 4
AntiAlias=1

; ----------------------------------------------------
; DAY
; ----------------------------------------------------

[MeterDay]
Meter=String
MeasureName=MeasureDay
StringAlign=Center
StringCase=Upper
FontFace=#FontMain#
FontColor=#TextColor#
FontSize=(62*#Scale#)
X=(115*#Scale#)
Y=(25*#Scale#)
Text="%1"
InlineSetting=LineSpacing | -10
AntiAlias=1

; ----------------------------------------------------
; TIME
; ----------------------------------------------------

[MeterTime]
Meter=String
MeasureName=MeasureTime
StringAlign=Center
FontFace=#FontSub#
FontColor=#TextColor#
FontSize=(30*#Scale#)
X=(115*#Scale#)
Y=(315*#Scale#)
Text="%1"
AntiAlias=1

; ----------------------------------------------------
; RIGHT VERTICAL LINE
; ----------------------------------------------------

[MeterRightLine]
Meter=Shape
Shape=Line 0,0,0,(290*#Scale#) | StrokeWidth 3 | Stroke Color #LineColor#
X=(200*#Scale#)
Y=(55*#Scale#)